import Head from "next/head";

const Index = () => {
  return (
    <>
      <Head>
        <title>Ruby Garage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>123</main>
    </>
  );
};

export default Index;
